blank_issues_enabled: true
contact_links:
  - name: Questions and support
    url: https://github.com/MaxAndreev27/vue-dashboard/issues
    about: Please use issues for support questions and general help.
