// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AuthenticationV1LoginForAccessTokenData, AuthenticationV1LoginForAccessTokenErrors, AuthenticationV1LoginForAccessTokenResponses, HeroesV1CreateHeroData, HeroesV1CreateHeroErrors, HeroesV1CreateHeroResponses, HeroesV1DeleteHeroData, HeroesV1DeleteHeroErrors, HeroesV1DeleteHeroResponses, HeroesV1ReadHeroData, HeroesV1ReadHeroErrors, HeroesV1ReadHeroesData, HeroesV1ReadHeroesErrors, HeroesV1ReadHeroesResponses, HeroesV1ReadHeroResponses, HeroesV1UpdateHeroData, HeroesV1UpdateHeroErrors, HeroesV1UpdateHeroResponses, SystemRootData, SystemRootResponses, UsersV1DeleteUserData, UsersV1DeleteUserErrors, UsersV1DeleteUserResponses, UsersV1ReadUserData, UsersV1ReadUserErrors, UsersV1ReadUserResponses, UsersV1ReadUsersData, UsersV1ReadUsersErrors, UsersV1ReadUsersMeData, UsersV1ReadUsersMeResponses, UsersV1ReadUsersResponses, UsersV1RegisterUserData, UsersV1RegisterUserErrors, UsersV1RegisterUserResponses, UsersV1UpdateUserData, UsersV1UpdateUserErrors, UsersV1UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Root
 */
export const systemRoot = <ThrowOnError extends boolean = false>(options?: Options<SystemRootData, ThrowOnError>): RequestResult<SystemRootResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SystemRootResponses, unknown, ThrowOnError>({ url: '/api/v1/', ...options });

/**
 * Login For Access Token
 */
export const authenticationV1LoginForAccessToken = <ThrowOnError extends boolean = false>(options: Options<AuthenticationV1LoginForAccessTokenData, ThrowOnError>): RequestResult<AuthenticationV1LoginForAccessTokenResponses, AuthenticationV1LoginForAccessTokenErrors, ThrowOnError> => (options.client ?? client).post<AuthenticationV1LoginForAccessTokenResponses, AuthenticationV1LoginForAccessTokenErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/v1/auth/token',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Read Users
 */
export const usersV1ReadUsers = <ThrowOnError extends boolean = false>(options?: Options<UsersV1ReadUsersData, ThrowOnError>): RequestResult<UsersV1ReadUsersResponses, UsersV1ReadUsersErrors, ThrowOnError> => (options?.client ?? client).get<UsersV1ReadUsersResponses, UsersV1ReadUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/',
    ...options
});

/**
 * Register User
 *
 * Реєстрація нового користувача з безпечним збереженням хэшу пароля в БД.
 */
export const usersV1RegisterUser = <ThrowOnError extends boolean = false>(options: Options<UsersV1RegisterUserData, ThrowOnError>): RequestResult<UsersV1RegisterUserResponses, UsersV1RegisterUserErrors, ThrowOnError> => (options.client ?? client).post<UsersV1RegisterUserResponses, UsersV1RegisterUserErrors, ThrowOnError>({
    url: '/api/v1/users/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Users Me
 */
export const usersV1ReadUsersMe = <ThrowOnError extends boolean = false>(options?: Options<UsersV1ReadUsersMeData, ThrowOnError>): RequestResult<UsersV1ReadUsersMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<UsersV1ReadUsersMeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/',
    ...options
});

/**
 * Delete User
 */
export const usersV1DeleteUser = <ThrowOnError extends boolean = false>(options: Options<UsersV1DeleteUserData, ThrowOnError>): RequestResult<UsersV1DeleteUserResponses, UsersV1DeleteUserErrors, ThrowOnError> => (options.client ?? client).delete<UsersV1DeleteUserResponses, UsersV1DeleteUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{user_id}',
    ...options
});

/**
 * Read User
 */
export const usersV1ReadUser = <ThrowOnError extends boolean = false>(options: Options<UsersV1ReadUserData, ThrowOnError>): RequestResult<UsersV1ReadUserResponses, UsersV1ReadUserErrors, ThrowOnError> => (options.client ?? client).get<UsersV1ReadUserResponses, UsersV1ReadUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{user_id}',
    ...options
});

/**
 * Update User
 */
export const usersV1UpdateUser = <ThrowOnError extends boolean = false>(options: Options<UsersV1UpdateUserData, ThrowOnError>): RequestResult<UsersV1UpdateUserResponses, UsersV1UpdateUserErrors, ThrowOnError> => (options.client ?? client).patch<UsersV1UpdateUserResponses, UsersV1UpdateUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Heroes
 */
export const heroesV1ReadHeroes = <ThrowOnError extends boolean = false>(options?: Options<HeroesV1ReadHeroesData, ThrowOnError>): RequestResult<HeroesV1ReadHeroesResponses, HeroesV1ReadHeroesErrors, ThrowOnError> => (options?.client ?? client).get<HeroesV1ReadHeroesResponses, HeroesV1ReadHeroesErrors, ThrowOnError>({ url: '/api/v1/heroes/', ...options });

/**
 * Create Hero
 */
export const heroesV1CreateHero = <ThrowOnError extends boolean = false>(options: Options<HeroesV1CreateHeroData, ThrowOnError>): RequestResult<HeroesV1CreateHeroResponses, HeroesV1CreateHeroErrors, ThrowOnError> => (options.client ?? client).post<HeroesV1CreateHeroResponses, HeroesV1CreateHeroErrors, ThrowOnError>({
    url: '/api/v1/heroes/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Hero
 */
export const heroesV1DeleteHero = <ThrowOnError extends boolean = false>(options: Options<HeroesV1DeleteHeroData, ThrowOnError>): RequestResult<HeroesV1DeleteHeroResponses, HeroesV1DeleteHeroErrors, ThrowOnError> => (options.client ?? client).delete<HeroesV1DeleteHeroResponses, HeroesV1DeleteHeroErrors, ThrowOnError>({ url: '/api/v1/heroes/{hero_id}', ...options });

/**
 * Read Hero
 */
export const heroesV1ReadHero = <ThrowOnError extends boolean = false>(options: Options<HeroesV1ReadHeroData, ThrowOnError>): RequestResult<HeroesV1ReadHeroResponses, HeroesV1ReadHeroErrors, ThrowOnError> => (options.client ?? client).get<HeroesV1ReadHeroResponses, HeroesV1ReadHeroErrors, ThrowOnError>({ url: '/api/v1/heroes/{hero_id}', ...options });

/**
 * Update Hero
 */
export const heroesV1UpdateHero = <ThrowOnError extends boolean = false>(options: Options<HeroesV1UpdateHeroData, ThrowOnError>): RequestResult<HeroesV1UpdateHeroResponses, HeroesV1UpdateHeroErrors, ThrowOnError> => (options.client ?? client).patch<HeroesV1UpdateHeroResponses, HeroesV1UpdateHeroErrors, ThrowOnError>({
    url: '/api/v1/heroes/{hero_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
