// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_Authentication V1-login_for_access_token
 */
export type BodyAuthenticationV1LoginForAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeroCreate
 */
export type HeroCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Secret Name
     */
    secret_name: string;
};

/**
 * HeroPublic
 */
export type HeroPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Id
     */
    id: number;
};

/**
 * HeroUpdate
 */
export type HeroUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Secret Name
     */
    secret_name?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * User
 */
export type User = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Hashed Password
     */
    hashed_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Id
     */
    id?: number | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Disabled
     */
    disabled?: boolean | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SystemRootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/';
};

export type SystemRootResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthenticationV1LoginForAccessTokenData = {
    body: BodyAuthenticationV1LoginForAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token';
};

export type AuthenticationV1LoginForAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthenticationV1LoginForAccessTokenError = AuthenticationV1LoginForAccessTokenErrors[keyof AuthenticationV1LoginForAccessTokenErrors];

export type AuthenticationV1LoginForAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type AuthenticationV1LoginForAccessTokenResponse = AuthenticationV1LoginForAccessTokenResponses[keyof AuthenticationV1LoginForAccessTokenResponses];

export type UsersV1ReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersV1ReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersV1ReadUsersError = UsersV1ReadUsersErrors[keyof UsersV1ReadUsersErrors];

export type UsersV1ReadUsersResponses = {
    /**
     * Response Users V1-Read Users
     *
     * Successful Response
     */
    200: Array<UserPublic>;
};

export type UsersV1ReadUsersResponse = UsersV1ReadUsersResponses[keyof UsersV1ReadUsersResponses];

export type UsersV1RegisterUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/register';
};

export type UsersV1RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersV1RegisterUserError = UsersV1RegisterUserErrors[keyof UsersV1RegisterUserErrors];

export type UsersV1RegisterUserResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type UsersV1RegisterUserResponse = UsersV1RegisterUserResponses[keyof UsersV1RegisterUserResponses];

export type UsersV1ReadUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/';
};

export type UsersV1ReadUsersMeResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UsersV1ReadUsersMeResponse = UsersV1ReadUsersMeResponses[keyof UsersV1ReadUsersMeResponses];

export type UsersV1DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersV1DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersV1DeleteUserError = UsersV1DeleteUserErrors[keyof UsersV1DeleteUserErrors];

export type UsersV1DeleteUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersV1ReadUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersV1ReadUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersV1ReadUserError = UsersV1ReadUserErrors[keyof UsersV1ReadUserErrors];

export type UsersV1ReadUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersV1ReadUserResponse = UsersV1ReadUserResponses[keyof UsersV1ReadUserResponses];

export type UsersV1UpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersV1UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersV1UpdateUserError = UsersV1UpdateUserErrors[keyof UsersV1UpdateUserErrors];

export type UsersV1UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersV1UpdateUserResponse = UsersV1UpdateUserResponses[keyof UsersV1UpdateUserResponses];

export type HeroesV1ReadHeroesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/heroes/';
};

export type HeroesV1ReadHeroesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeroesV1ReadHeroesError = HeroesV1ReadHeroesErrors[keyof HeroesV1ReadHeroesErrors];

export type HeroesV1ReadHeroesResponses = {
    /**
     * Response Heroes V1-Read Heroes
     *
     * Successful Response
     */
    200: Array<HeroPublic>;
};

export type HeroesV1ReadHeroesResponse = HeroesV1ReadHeroesResponses[keyof HeroesV1ReadHeroesResponses];

export type HeroesV1CreateHeroData = {
    body: HeroCreate;
    path?: never;
    query?: never;
    url: '/api/v1/heroes/';
};

export type HeroesV1CreateHeroErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeroesV1CreateHeroError = HeroesV1CreateHeroErrors[keyof HeroesV1CreateHeroErrors];

export type HeroesV1CreateHeroResponses = {
    /**
     * Successful Response
     */
    200: HeroPublic;
};

export type HeroesV1CreateHeroResponse = HeroesV1CreateHeroResponses[keyof HeroesV1CreateHeroResponses];

export type HeroesV1DeleteHeroData = {
    body?: never;
    path: {
        /**
         * Hero Id
         */
        hero_id: number;
    };
    query?: never;
    url: '/api/v1/heroes/{hero_id}';
};

export type HeroesV1DeleteHeroErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeroesV1DeleteHeroError = HeroesV1DeleteHeroErrors[keyof HeroesV1DeleteHeroErrors];

export type HeroesV1DeleteHeroResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HeroesV1ReadHeroData = {
    body?: never;
    path: {
        /**
         * Hero Id
         */
        hero_id: number;
    };
    query?: never;
    url: '/api/v1/heroes/{hero_id}';
};

export type HeroesV1ReadHeroErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeroesV1ReadHeroError = HeroesV1ReadHeroErrors[keyof HeroesV1ReadHeroErrors];

export type HeroesV1ReadHeroResponses = {
    /**
     * Successful Response
     */
    200: HeroPublic;
};

export type HeroesV1ReadHeroResponse = HeroesV1ReadHeroResponses[keyof HeroesV1ReadHeroResponses];

export type HeroesV1UpdateHeroData = {
    body: HeroUpdate;
    path: {
        /**
         * Hero Id
         */
        hero_id: number;
    };
    query?: never;
    url: '/api/v1/heroes/{hero_id}';
};

export type HeroesV1UpdateHeroErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeroesV1UpdateHeroError = HeroesV1UpdateHeroErrors[keyof HeroesV1UpdateHeroErrors];

export type HeroesV1UpdateHeroResponses = {
    /**
     * Successful Response
     */
    200: HeroPublic;
};

export type HeroesV1UpdateHeroResponse = HeroesV1UpdateHeroResponses[keyof HeroesV1UpdateHeroResponses];
